version: '3.9'
services:
  frontend:
    container_name: app-front-dev
    image: app-front-dev
    build: ./ArtShop-frontend
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./ArtShop-frontend
        target: /app
      - type: volume
        source: node_modules_volume
        target: /app/node_modules
    networks:
      - dev
  db:
    container_name: db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: artshop
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dev
  backend:
    container_name: app-backend-dev
    image: app-backend-dev
    build:
      context: ./ArtShop-backend
    ports:
      - "8000:8000"
    env_file:
      - ./ArtShop-backend/.env.local
    restart: always
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./ArtShop-backend
        target: /var/www/html
      - type: volume
        source: vendor_volume
        target: /var/www/html/vendor
    networks:
      - dev
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: pepa-linha
    depends_on:
      - db
    networks:
      - dev
networks:
  dev:


volumes:
  db_data:
  node_modules_volume:
  vendor_volume:
